baseURL = 'https://oboudry.github.io/'
languageCode = 'en-us'
title = 'Kube & Co'
theme = "beautifulhugo"
[Author]
  name = "Olivier Boudry"
  website = "https://oboudry.github.io/kube-and-co/"
  github = "oboudry/kube-and-co"
